"""Host protocol for exclusive tools. Window implements this; tools do not import it."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ToolHost(Protocol):
    game: object
    mouse_x: float
    mouse_y: float
    mouse_in_window: bool
    zoom_scale: float
    view_yaw_q: int
    grass_close_enabled: bool

    @property
    def dialogs(self): ...

    @property
    def toolbar(self): ...

    @property
    def tile_set(self): ...

    @property
    def window_size(self) -> tuple[float, float]: ...

    def grid_cell_at(self, sx: float, sy: float) -> tuple[int, int]: ...

    def cell_on_map(self, cell: tuple[int, int]) -> bool: ...

    def cell_is_grass(self, cell: tuple[int, int]) -> bool: ...

    def to_screen(self, gx: float, gy: float, center_x: float, center_y: float) -> tuple[float, float]: ...

    @property
    def pan_fly(self) -> bool: ...

    @property
    def space_panning(self) -> bool: ...

    def toggle_pan_fly(self) -> str: ...

    def begin_camera_grab(self, x: float, y: float) -> None: ...

    def update_camera_grab(self, x: float, y: float) -> None: ...

    def end_camera_grab(self) -> None: ...

    def begin_camera_fly(self, x: float, y: float) -> None: ...

    def end_camera_fly(self) -> None: ...

    def begin_zoom_drag(self, x: float, y: float) -> None: ...

    def update_zoom_drag(self, x: float, y: float) -> None: ...

    def end_zoom_drag(self) -> None: ...

    def orbit_camera_at(self, x: float, y: float, clockwise: bool) -> None: ...

    def on_config_change(self, rebuild_world: bool = False) -> None: ...

    def sync_toolbar_bottom(self) -> None: ...

    def place_at_screen(self, sx: float, sy: float) -> str | None: ...

    def car_at_screen(self, sx: float, sy: float): ...

    def nearest_car_at_screen(self, sx: float, sy: float): ...

    def lane_at_screen(self, sx: float, sy: float) -> int | None: ...

    def intersection_at_screen(self, sx: float, sy: float) -> str | None: ...

    def on_place_renamed(self, old: str, new: str) -> None: ...

    def forget_place_dialog(self, place: str) -> None: ...

    def forget_lane_dialog(self, lane_idx: int) -> None: ...

    def forget_intersection_dialog(self, key: str) -> None: ...

    def cached_place_dialog(self, place: str): ...

    def store_place_dialog(self, place: str, dlg) -> None: ...

    def cached_lane_dialog(self, lane_idx: int): ...

    def store_lane_dialog(self, lane_idx: int, dlg) -> None: ...

    def cached_intersection_dialog(self, key: str): ...

    def store_intersection_dialog(self, key: str, dlg) -> None: ...
